// Generated by scripts/coarsen-references.mjs. Do not edit by hand.
// Each sprite is stored at the size it is drawn at, 1.5 sprite pixel(s) per scene unit, so it
// shares the room's pixel grid; the app upscales it with image-rendering: pixelated. `units` is that
// size in scene units, and pivot is how far the sprite's middle sits from the point it was
// rotated around, for the framed pair the room places by their shared centre.
export const REFRESHED_SPRITES = {
  'alhazard': { file: 'alhazard-px.png', w: 39, h: 57, units: { w: 26, h: 38 }, pivot: { dx: 1.08, dy: -0.29 } },
  'langrisser': { file: 'langrisser-px.png', w: 37, h: 55, units: { w: 24.67, h: 36.67 }, pivot: { dx: -0.13, dy: 0 } },
  'gran': { file: 'gran-px.png', w: 31, h: 74, units: { w: 20.67, h: 49.33 }, pivot: { dx: 0, dy: 0 } },
  'armageddon': { file: 'armageddon-px.png', w: 66, h: 13, units: { w: 44, h: 8.67 }, pivot: { dx: 0, dy: 0 } },
  'seer': { file: 'seer-px.png', w: 32, h: 50, units: { w: 21.33, h: 33.33 }, pivot: { dx: 0, dy: 0 } },
  'alpha': { file: 'alpha-px.png', w: 36, h: 46, units: { w: 24, h: 30.67 }, pivot: { dx: 0, dy: 0 } },
  'master-ball': { file: 'master-ball-px.png', w: 30, h: 29, units: { w: 20, h: 19.33 }, pivot: { dx: 0, dy: 0 } },
} as const

export type RefreshedKind = keyof typeof REFRESHED_SPRITES
